### ISSUE TITLE
validate 1.25.0-SNAPSHOT raises an exception when validating a product

### ISSUE THREAD

**Issue by fran-vallejo** [NASA-PDS/validate#271]
**Describe the bug**
validate 1.25.0-SNAPSHOT raises a **BufferUnderflowException** when validating the product attached, but this product validates fine with 1.24.0.
This is a follow-up to [pds4-jparser#21](https://github.com/NASA-PDS/pds4-jparser/issues/21).

**Version of Software Used**
Validate 1.25.0-SNAPSHOT build from the current master of both pds4-jparser and validate, specifically from:
- pds4-jparser commit **f1587d94e3ac0115e872b31202c3b4aa613e9c15**
- validate commit          **a5d6021e3eb64601e6126c792bb7e7a31e67de4b**

**Test Data / Additional context**
You can download the problematic product from: (The link will be live until Dec. 15th)
https://esabox.esa.int/owncloud/index.php/s/xLlWOJMSRVDWW2s
Pass: Jparser#21

**To Reproduce**
Run validate 1.25.0-SNAPSHOT with the attached product as input.
```
PDS Validate Tool Report

Configuration:
   Version                       1.25.0-SNAPSHOT
   Date                          2020-12-03T17:33:06Z

Parameters:
   Targets                       [file:/home/fvallejo/Downloads/mag/mag_cal_sc_ob_s9_e2k_00000_20181105.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /home/fvallejo/Software/validate-1.25.0-SNAPSHOT/resources/registered_context_products.json
   Non Registered Contexts File  /home/fvallejo/git/local_context_products.json



Product Level Validation Results

  PASS: gov.nasa.pds.validate.ValidateLauncher
      WARNING  [warning.product_not_registered]   Non-registered context products should only be used during archive development. All context products must be registered for a valid, released archive bundle. 
        1 product validation(s) completed
....................................................................java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
	at gov.nasa.pds.tools.validate.task.ValidationTask.execute(ValidationTask.java:134)
	at gov.nasa.pds.tools.validate.task.BlockingTaskManager.submit(BlockingTaskManager.java:27)
	at gov.nasa.pds.tools.label.LocationValidator.validate(LocationValidator.java:236)
	at gov.nasa.pds.validate.ValidateLauncher.doValidation(ValidateLauncher.java:1256)
	at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1494)
	at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1540)
Caused by: java.nio.BufferUnderflowException
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:271)
	at java.nio.ByteBuffer.get(ByteBuffer.java:715)
	at gov.nasa.pds.objectAccess.ByteWiseFileAccessor.readRecordBytes(ByteWiseFileAccessor.java:237)
	at gov.nasa.pds.objectAccess.TableReader.getTableRecord(TableReader.java:233)
	at gov.nasa.pds.objectAccess.TableReader.getRecord(TableReader.java:214)
	at gov.nasa.pds.tools.validate.content.table.RawTableReader.getRecord(RawTableReader.java:173)
	at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.validateTableDataContents(TableDataContentValidationRule.java:467)
	... 12 more

  FAIL: file:/home/fvallejo/Downloads/mag/mag_cal_sc_ob_s9_e2k_00000_20181105.xml
      ERROR  [error.validation.internal_error]   Error executing validationTask: java.nio.BufferUnderflowException
        2 product validation(s) completed

Summary:

  1 error(s)
  1 warning(s)

  Product Validation Summary:
    1          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    1            error.validation.internal_error
    1            warning.product_not_registered

End of Report
Completed execution in 157130 ms

```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Java 1.8.0_201 (build 1.8.0_201-b09)

**Related Issues**
NASA-PDS/pds4-jparser#21

**Comment by jordanpadams** [comment]
@qchaupds I think we actually want to do this ticket next because it is a bug per a fix we put in a while back.

Related to this ticket: NASA-PDS/pds4-jparser#21

And these pull requests for applicable changes:
validate #268
NASA-PDS/pds4-jparser#31

**Comment by qchaupds** [comment]
Ignore the comments in the last commit. 

https://github.com/NASA-PDS/pds4-jparser/commit/e5cd660ad9a06d767926dded03c51eb560c097a3

They should be:

New code to support #271: validate 1.25.0-SNAPSHOT raises an exception when validating a product
1. Add logic to handle when a record spans over two mappings in large file in ByteWiseFileAccessor.java
2. Add debug statements in TableReader.java

**Comment by jordanpadams** [comment]
@fran-vallejo pds4 jparser should now include this fix. let us know if you come across any more issues!
