### ISSUE TITLE
Bug performing bundle validation with nested directories

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#273]
Related to #271? Validate dies here when data_hst/ has labels in data_hst/dn/ rather than at the top level.
[bad.zip](https://github.com/NASA-PDS/validate/files/5670957/bad.zip)

% validate --version
gov.nasa.pds:validate
Version 1.25.0-SNAPSHOT
Release Date: 2020-12-09 02:55:20
Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.
% 
% 
% validate -R pds4.bundle -t bad
net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; systemId: file:/Volumes/4TB/Desktop/psi/bad/data_hst/dn/; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:455)
	at net.sf.saxon.event.Sender.send(Sender.java:141)
	at net.sf.saxon.Configuration.buildDocumentTree(Configuration.java:4236)
	at net.sf.saxon.Configuration.buildDocument(Configuration.java:4319)
	at gov.nasa.pds.tools.util.LabelParser.parse(LabelParser.java:42)
	at gov.nasa.pds.tools.validate.TargetExaminer.getTargetContent(TargetExaminer.java:164)
	at gov.nasa.pds.tools.validate.BundleManager.selectMatchingReferenceFromCollection(BundleManager.java:231)
	at gov.nasa.pds.tools.validate.BundleManager.findCollectionWithMatchingReference(BundleManager.java:300)
	at gov.nasa.pds.tools.validate.BundleManager.buildCollectionIgnoreList(BundleManager.java:360)
	at gov.nasa.pds.tools.label.LocationValidator.validate(LocationValidator.java:202)
	at gov.nasa.pds.validate.ValidateLauncher.doValidation(ValidateLauncher.java:1256)
	at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1494)
	at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1540)
Caused by: org.xml.sax.SAXParseException; systemId: file:/Volumes/4TB/Desktop/psi/bad/data_hst/dn/; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:435)
	... 12 more
---------
org.xml.sax.SAXParseException; systemId: file:/Volumes/4TB/Desktop/psi/bad/data_hst/dn/; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:435)
	at net.sf.saxon.event.Sender.send(Sender.java:141)
	at net.sf.saxon.Configuration.buildDocumentTree(Configuration.java:4236)
	at net.sf.saxon.Configuration.buildDocument(Configuration.java:4319)
	at gov.nasa.pds.tools.util.LabelParser.parse(LabelParser.java:42)
	at gov.nasa.pds.tools.validate.TargetExaminer.getTargetContent(TargetExaminer.java:164)
	at gov.nasa.pds.tools.validate.BundleManager.selectMatchingReferenceFromCollection(BundleManager.java:231)
	at gov.nasa.pds.tools.validate.BundleManager.findCollectionWithMatchingReference(BundleManager.java:300)
	at gov.nasa.pds.tools.validate.BundleManager.buildCollectionIgnoreList(BundleManager.java:360)
	at gov.nasa.pds.tools.label.LocationValidator.validate(LocationValidator.java:202)
	at gov.nasa.pds.validate.ValidateLauncher.doValidation(ValidateLauncher.java:1256)
	at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1494)
	at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1540)
PDS Validate Tool Report
Configuration:
   Version                       1.25.0-SNAPSHOT
   Date                          2020-12-10T06:58:39Z
Parameters:
   Targets                       [file:/Volumes/4TB/Desktop/psi/bad/]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  FAIL: file:/Volumes/4TB/Desktop/psi/bad/
      FATAL_ERROR  [error.validation.internal_error]   Index 0 out of bounds for length 0
Summary:
  1 error(s)
  0 warning(s)
  Product Validation Summary:
    0          product(s) passed
    0          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
  Message Types:
    1            error.validation.internal_error
End of Report

However, if I move files out of the subdirectory, validate works

% mv bad/data_hst/dn/* bad/data_hst
% rmdir bad/data_hst/dn
% validate -R pds4.bundle -t bad
PDS Validate Tool Report
Configuration:
   Version                       1.25.0-SNAPSHOT
   Date                          2020-12-10T07:21:33Z
Parameters:
   Targets                       [file:/Volumes/4TB/Desktop/psi/bad/]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  FAIL: file:/Volumes/4TB/Desktop/psi/bad/bundle_ast.uv.reflectance-spectra.xml
      ERROR  [error.label.context_ref_not_found]   line 107: 'Context product not found: urn:nasa:pds:context:instrument:mmt.single_mirror6m5.bluespec
        1 product validation(s) completed
  PASS: file:/Volumes/4TB/Desktop/psi/bad/data_hst/collection_data_hst.xml
        2 product validation(s) completed
  PASS: file:/Volumes/4TB/Desktop/psi/bad/data_hst/spec_01_000_dn.xml
        3 product validation(s) completed
  PASS: file:/Volumes/4TB/Desktop/psi/bad/data_hst/spec_01_001_dn.xml
        4 product validation(s) completed
PDS4 Bundle Level Validation Results
  PASS: file:/Volumes/4TB/Desktop/psi/bad/data_hst/collection_data_hst.xml
        1 integrity check(s) completed
  PASS: file:/Volumes/4TB/Desktop/psi/bad/bundle_ast.uv.reflectance-spectra.xml
        2 integrity check(s) completed
  PASS: file:/Volumes/4TB/Desktop/psi/bad/data_hst/spec_01_000_dn.xml
        3 integrity check(s) completed
  PASS: file:/Volumes/4TB/Desktop/psi/bad/data_hst/spec_01_001_dn.xml
        4 integrity check(s) completed
Summary:
  1 error(s)
  0 warning(s)
  Product Validation Summary:
    3          product(s) passed
    1          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    4          check(s) passed
    0          check(s) failed
    0          check(s) skipped
  Message Types:
    1            error.label.context_ref_not_found
End of Report
Completed execution in 5331 ms

**Comment by jordanpadams** [comment]
@qchaupds let's actually work on this next. looks like possibly an issue with how we are doing our bundle validation. possibly related to #254 or #238

**Comment by jordanpadams** [comment]
@rchenatjpl we think this was an easy bug to squash. @qchaupds was right on it. let us know if the latest SNAPSHOT works for you (maybe wait 5 minutes while it builds...)

**Comment by rchenatjpl** [comment]
looks good to me
