### ISSUE TITLE
validate2.0.3 throws unexpected JavaExceptions, and after fix, it hangs when trying bundle validation

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#336]
validate2.0.3 throws errors that 2.0.2 doesn't. The errors probably don't exist.

% ../../PDS4.11.1.tools/validate-2.0.2/bin/validate -R pds4.bundle -t VG1-J-POS-6-SUMM-HGCOORDS-V1.0

PDS Validate Tool Report

Configuration:
   Version                       2.0.2
   Date                          2021-05-04T22:42:35Z

Parameters:
   Targets                       [file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4.11.1.tools/validate-2.0.2/resources/registered_context_products.json

Product Level Validation Results

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/bundle-vg1-jup-pos-hgcoords-1.0.xml
        1 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/data_sedr/SEDR057_078.xml
        2 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/data_sedr/collection-data-sedr-1.0.xml
        3 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/data_spice/collection-data-spice-1.0.xml
        4 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/data_spice/SPICE057_078.xml
        5 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/document/Dataset.xml
        6 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/document/collection-document-1.0.xml
        7 product validation(s) completed

PDS4 Bundle Level Validation Results

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/data_sedr/collection-data-sedr-1.0.xml
        1 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/data_spice/collection-data-spice-1.0.xml
        2 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/document/collection-document-1.0.xml
        3 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/bundle-vg1-jup-pos-hgcoords-1.0.xml
        4 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/data_sedr/SEDR057_078.xml
        5 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/data_spice/SPICE057_078.xml
        6 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/document/Dataset.xml
        7 integrity check(s) completed

Summary:

  0 error(s)
  0 warning(s)

  Product Validation Summary:
    7          product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    7          check(s) passed
    0          check(s) failed
    0          check(s) skipped

End of Report
Completed execution in 7499 ms

% 
% 
% ../../PDS4.11.1.tools/validate-2.0.3/bin/validate -R pds4.bundle -t VG1-J-POS-6-SUMM-HGCOORDS-V1.0

PDS Validate Tool Report

Configuration:
   Version                       2.0.3
   Date                          2021-05-04T22:43:00Z

Parameters:
   Targets                       [file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4.11.1.tools/validate-2.0.3/resources/registered_context_products.json

Product Level Validation Results

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/bundle-vg1-jup-pos-hgcoords-1.0.xml
        1 product validation(s) completed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
	at gov.nasa.pds.tools.validate.rule.pds4.LabelInFolderRule$1.run(LabelInFolderRule.java:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException
	at gov.nasa.pds.tools.validate.rule.RuleContext.getCheckInbetweenFields(RuleContext.java:427)
	at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.getCheckInbetweenFields(TableDataContentValidationRule.java:115)
	at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.validateTableDataContents(TableDataContentValidationRule.java:397)
	... 12 more

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/data_sedr/collection-data-sedr-1.0.xml
        2 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/data_spice/collection-data-spice-1.0.xml
        3 product validation(s) completed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
	at gov.nasa.pds.tools.validate.rule.pds4.LabelInFolderRule$1.run(LabelInFolderRule.java:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException
	at gov.nasa.pds.tools.validate.rule.RuleContext.getCheckInbetweenFields(RuleContext.java:427)
	at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.getCheckInbetweenFields(TableDataContentValidationRule.java:115)
	at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.validateTableDataContents(TableDataContentValidationRule.java:397)
	... 12 more

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/document/Dataset.xml
        4 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/document/collection-document-1.0.xml
        5 product validation(s) completed

PDS4 Bundle Level Validation Results

  FAIL: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/data_sedr/SEDR057_078.xml
      ERROR  [error.validation.internal_error]   Uncaught exception while validating: null
        1 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/data_sedr/collection-data-sedr-1.0.xml
        2 integrity check(s) completed

  FAIL: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/data_spice/SPICE057_078.xml
      ERROR  [error.validation.internal_error]   Uncaught exception while validating: null
        3 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/data_spice/collection-data-spice-1.0.xml
        4 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/document/collection-document-1.0.xml
        5 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/bundle-vg1-jup-pos-hgcoords-1.0.xml
        6 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/ppi/VG1-J-POS-6-SUMM-HGCOORDS-V1.0/document/Dataset.xml
        7 integrity check(s) completed

Summary:

  2 error(s)
  0 warning(s)

  Product Validation Summary:
    5          product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    5          check(s) passed
    2          check(s) failed
    0          check(s) skipped

  Message Types:
    2            error.validation.internal_error

End of Report
Completed execution in 7670 ms
[VG1-J-POS-6-SUMM-HGCOORDS-V1.0.zip](https://github.com/NASA-PDS/validate/files/6424300/VG1-J-POS-6-SUMM-HGCOORDS-V1.0.zip)

**Comment by jordanpadams** [comment]
Thanks @rchenatjpl . I think this may be the same bug found in #335 . @msbentley may have beat you tot he punch. We think we have a fix, but also working on #325 at the same time

**Comment by jordanpadams** [comment]
duplicate of #335

**Comment by jordanpadams** [comment]
original fix in PR #338 works for Java11+ but not Java8. 14a675a should fix the problem with java8.
